#!/bin/bash

DIR="$HOME/Pictures/wallpapers/wallpapers/"
# mapfile -t PICS < <(ls "$DIR")
mapfile -t PICS < <(find "$DIR" -maxdepth 1 -type f -print)
# a link to all wallpaper
TARGET="$HOME/.config/hypr/scripts/wallpaper.link"

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

# init swww
swww query || swww init

# change wallpaper

ln -sf "$RANDOMPICS" "$TARGET"

swww img "$TARGET" --transition-fps 90 --transition-type any --transition-duration 5
