#!/bin/bash

DIR=$HOME/Pictures/wallpapers/wallpapers/
PICS=($(ls ${DIR}))
# a link to all wallpaper
TARGET=~/.config/hypr/scripts/wallpaper.link

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

# init swww
swww query || swww init

# change wallpaper

ln -sf ${DIR}/${RANDOMPICS} ${TARGET}

swww img ${TARGET} --transition-fps 90 --transition-type any --transition-duration 5
