[helpers]

[default]
depends = []

[default.files]


hypr = "~/.config/hypr/"
nvim = "~/.config/nvim/"
rofi = "~/.config/rofi/"
yazi = "~/.config/yazi/"
dunst = "~/.config/dunst/"
ricemood = "~/.config/ricemood/"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/oh-my-zsh" = "~/.oh-my-zsh/"
"zsh/fzf-tab" = "~/.config/fzf-tab/"
"zsh/fzf-tab-source" = "~/.config/fzf-tab-source"


[default.variables]
