# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# Enable Powerlevel9k instant prompt. Should stay close to the top of ~/.zshrc.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
# ZSH_THEME="powerlevel10k/powerlevel10k"
# [[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh
bindkey -e  # 强制使用 Emacs/Bash 风格绑定
source ~/.config/zsh/alias.zsh
source ~/.config/zsh/export.zsh
source ~/.config/zsh/function.zsh



source ~/.config/zsh/theme.zsh
source ~/.config/zsh/plugins.zsh



# 启用命令执行时长记录
setopt INC_APPEND_HISTORY_TIME

# 确保禁用其他可能导致时长为0的选项 (如果它们被默认或Oh My Zsh启用)
unsetopt INC_APPEND_HISTORY
unsetopt SHARE_HISTORY


# zinit snippet <(COMPLETE=zsh jj)
source ~/.config/zsh/eval.zsh
export WORKING_PATH=/home/mx/Code/python/DiffusionDrive/
export NUPLAN_MAP_VERSION="nuplan-maps-v1.0"
export NUPLAN_MAPS_ROOT="${WORKING_PATH}/dataset/maps"
export NAVSIM_EXP_ROOT="${WORKING_PATH}/exp"
export NAVSIM_DEVKIT_ROOT="${WORKING_PATH}"
export OPENSCENE_DATA_ROOT="${WORKING_PATH}/dataset"
