timeline_style=bar
timeline_size=46
timeline_border=0
timeline_cache=no
timeline_heatmap=no
progress=never
controls=space,command:subtitles:cycle sub,toggle:volume_up:mute,fullscreen
controls_size=34
controls_margin=12
controls_spacing=6
volume=none
top_bar=never
window_border_size=0
bottom_gap=28
scale_fullscreen=1
text_border=1
border_radius=8
color=foreground=39c5bb,foreground_text=0f172a,background=5b6472,background_text=f3f4f6,curtain=111827,success=39c5bb,error=ff7a90,match=39c5bb,heatmap=39c5bb
opacity=timeline=0.82,position=1,chapters=0.8,slider=0.9,slider_gauge=1,controls=0.34,speed=0.6,menu=0.96,submenu=0.55,border=1,title=1,tooltip=1,thumbnail=1,curtain=0.72,idle_indicator=0.8,audio_indicator=0.5,buffering_indicator=0.22,playlist_position=0.85,heatmap=0.3
animation_duration=140
destination_time=total
time_precision=0
autohide=yes
chapter_ranges=
disable_elements=idle_indicator,audio_indicator,buffering_indicator,pause_indicator
