hl.curve("md3Decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3Accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("softAcDecel", { type = "bezier", points = { { 0.26, 0.26 }, { 0.15, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 2.6, bezier = "softAcDecel" })
hl.animation({ leaf = "windows", enabled = true, speed = 2.6, bezier = "softAcDecel" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.8, bezier = "md3Decel", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.0, bezier = "md3Accel", style = "slide" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.5, bezier = "md3Decel" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.2, bezier = "md3Accel" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.2, bezier = "softAcDecel" })
hl.animation({ leaf = "layers", enabled = true, speed = 2.4, bezier = "softAcDecel" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2.0, bezier = "md3Decel", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.4, bezier = "md3Accel", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.2, bezier = "md3Decel" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.0, bezier = "md3Accel" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.4, bezier = "softAcDecel", style = "slidefadevert 12%" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 2.4, bezier = "softAcDecel", style = "slidefadevert 12%" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.9, bezier = "md3Accel", style = "slidefadevert 12%" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 6, bezier = "softAcDecel" })
