hl.on("hyprland.start", function()
  hl.exec_cmd("clash-verge", { workspace = "9", no_initial_focus = true })
  hl.exec_cmd("SPlayer", { workspace = "10" })
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("mako")
  hl.exec_cmd("ashell")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("nwg-look -a")
  hl.exec_cmd("/usr/lib/mate-polkit/polkit-mate-authentication-agent-1")
  hl.exec_cmd("sleep 2 && $HOME/.config/hypr/scripts/clipboard.sh")
  hl.exec_cmd("hyprsunset")
  hl.exec_cmd("hyprlauncher -d")
end)
