# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# window be opacity
windowrule= match:class kitty,                       opacity 0.8
windowrule= match:class QQ,                          opacity 0.8
windowrule= match:class Session: New Session,        opacity 0.8
windowrule= match:class Rofi,                        opacity 0.8
windowrule= match:class thunar,                      opacity 0.8
windowrule= match:class org.kde.okular,              opacity 0.8
windowrule= match:class org.pwmt.zathura,            opacity 0.8
windowrule= match:class dev.zed.Zed,                 opacity 0.8
windowrule= match:class zen,                         opacity 0.8
windowrule= match:class chromium,                    opacity 0.8
windowrule= match:class Microsoft-edge,              opacity 0.8
windowrule= match:class google-chrome,               opacity 0.8
windowrule= match:class Alacritty,                   opacity 0.8
windowrule= match:class Code,                        opacity 0.8
windowrule= match:class com.mitchellh.ghostty,       opacity 0.8
windowrule= match:class yesplaymusic,                opacity 0.8
windowrule= match:class org.telegram.desktop,        opacity 0.8

windowrule= match:title 图片查看器,                  float on
windowrule= match:title (Volume Control),            float on
windowrule= match:title All Files,                   float on
windowrule= match:title satty,                       float on
windowrule= match:title Friends List,                float on
windowrule= match:title anki,                        float on
windowrule= match:title aitest-tauri,                float on
windowrule= match:title + 1 Chat,                    float on

windowrule= match:class SPlayer, workspace 10
windowrule= match:class SPlayer, no_initial_focus on


windowrule {
    name = "浮动窗口无边框"
    border_size = 0
    match:float = true
}

windowrule {
    name = splyer 
    match:title = SPlayer - 桌面歌词
    pin = on
    no_blur = true
    no_focus = on
    float = on
    no_initial_focus = on
    no_follow_mouse = on
    border_size = 0
}


# window float

# # window size 
# windowrule = size[80% 90%], title:(satty)
# windowrule = size[80% 90%], title:(anki)
#
# # window center
# windowrule = center 1, title:(satty)
#
# # workspace Rules
# workspace = s[1], gapsin:10, gapsout:90
#
# # Layers
#
# # layerrule = blur, swww-daemon
# windowrulev2 = workspace 3 silent, noinitialfocus, class:.*tauri$

# windowrulev2 = stayfocused, class:^(desktop-lyrics)$

